build:
  script:
  - mvn clean install --settings /home/gitlab-runner/settings.xml
  artifacts:
    paths:
    - $CI_PROJECT_DIR/*/target/*.jar
  only:
  - master
  stage: build

deploy:
  script:
  - mvn deploy --settings /home/gitlab-runner/settings.xml
  only:
  - master
  stage: deploy

pages:
  script:
  - mvn javadoc:aggregate -pl :mcone-cloud,:core,:core-api,:host-api,:network-api
  - mkdir .public
  - cp -r $CI_PROJECT_DIR/target/site/apidocs/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  stage: deploy