build:
  script:
  - mvn --settings /home/gitlab-runner/settings.xml clean install
  - mvn --settings /home/gitlab-runner/settings.xml deploy
  - ls
  artifacts:
    paths:
    - target/*.jar
  only:
  - master
  tags:
  - runner1
