ip_forward: true
network_compression_threshold: 256
stats: db551145-4c6a-4d7a-9dd8-deb5a3125bb7
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  rufi:
  - admin
  TwinsterHD:
  - admin
servers:
  Fallback:
    motd: '&f&lMC ONE &3CloudServer &8» &7FallbackServer'
    address: localhost:25566
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: '&f&lMC ONE &3CloudServer &8» &7Main-Proxy'
  priorities:
  - Fallback
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
  forced_hosts:
    localhost: Fallback
  proxy_protocol: false
prevent_proxy_connections: false
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
